### ISSUE TITLE
ReplayWebpage V2 Documentation Update

### ISSUE THREAD

**Issue by Shrinks99** [webrecorder/replayweb.page#250]
### Context

ReplayWebpage needs some documentation updates!  There are a few features that are undocumented and we also want to convert our documentation to mkdocs with a developer and user guide similar to Browsertrix.

### Todo
- [ ] ~#247~
- [x] Switch to mkdocs
  - [x] Decide if mkdocs config and vscode settings should also live under /docs in our repos, figure out what this might mean for readthedocs integration.
  - [x] #252 
- [ ] Set up docs.replayweb.page subdomain
- [ ] ~#257~
- [x] Update branding?
