### ISSUE TITLE
ReplayWebpage Branding Update

### ISSUE THREAD

**Issue by Shrinks99** [webrecorder/replayweb.page#291]
### Context

This issue has already become a little bigger than an asset swap.... TL;DR We have new branding now!  It's already rolled out in #278 and should also make its way into the app!

...But now that we're adding new assets, it might also be nice to overhaul how we address them in ReplayWebpage so that it's in-line with Browsertrix?  ~If we're going to deal with asset imports the same way, that means all of the font awesome icons imported as SVG code and not file paths _also_ have to change and so I figure it makes sense to transition to `<sl-icon>` at the same time.~

### Tasks
- [x] Finalize ReplayWebpage app icon for desktop & PWAs
- [x] ReplayWebpage in-app icon (for use with `sl-icon` both in Browsertrix and in the menu item)
- [x] Update favicons
- [x] Update the asset addressing system to use pathing with the TsconfigPathsPlugin
-  ~Relink SVGs now that importing them returns paths instead of SVG code~
    -  ~If I need to relink everything that is imported this way, it ALSO makes sense to use this time to switch to `sl-icon`~
- [x] Add the app logos under the new `src/assets/brand` folder, also matching Browsertrix!
- [x] Add static app icon for loading screen
